### ISSUE TITLE
use pixel sixe icons

### ISSUE THREAD

**Issue by varlesh** [psifidotos/nowdock-plasmoid#2]
Maybe better use standard pixel size value on slider?
16px, 22px, 32px, 48px, 64px, 128px and 256px.
It's comfortably.
Also i noticed icons always blurred on widget - icons not pixel alignment.

**Comment by varlesh** [comment]
Really 0px (on slider) - that not 48px (icons bigger).
**48px** that **-1px**
Please compare:
0px:

![image](https://cloud.githubusercontent.com/assets/8083855/17642612/2e57a400-6155-11e6-9950-5bf6536983b9.png)

-1px:
![image](https://cloud.githubusercontent.com/assets/8083855/17642609/1836fe28-6155-11e6-8747-206c074de708.png)

**Comment by psifidotos** [comment]
Using the default sizes,
it would solve this jump in the appearance... 

This jump (for 1px.) comes because I use PlasmaCore.IconItem in order to create the buffers.. And IconItem can not take intermediate values below 48px. just the default ones...

For my system I use as a Panel icon size the 64px. so I can shrink the icons from 48px. to 64px with no problem.

But changing this setting in the dialog in order for the user to choose just from the default ones, it would be much better I think...

**Comment by psifidotos** [comment]
--- "Also i noticed icons always blurred on widget"

can you explain me this also?

**Comment by varlesh** [comment]
--- "Also i noticed icons always blurred on widget"

if enable shadow - icons increase size and not have pixel alignment - blurred.

With shadow (-1px):
![image](https://cloud.githubusercontent.com/assets/8083855/17642826/282fde04-615e-11e6-99f4-861336922b71.png)

No shadow (-1px):
![image](https://cloud.githubusercontent.com/assets/8083855/17642832/4cede7ea-615e-11e6-9e01-bc2e29174eca.png)

**Comment by psifidotos** [comment]
with shadows enabled the image buffers are used and use exactly the correct pixel size,
with no shadows enabled IconItem element of Plasma is used and this is the reason of the difference...

with no shadows enabled changing the pixel size in negative values the icons decrease their size in steps..

12,24,32,48,64

also with no shadows enabled the animation is broken, it creates jump steps...

-- One way to solve this is to force shadows, I dont know for how many users no shadows is needed,
and changing the settings from small increase and decrease (+1, -1) to a list of the default sizes, should also resolve this...

**Comment by varlesh** [comment]
Note: 12px and 24px not used on KDE.
For example Oxygen icon theme (as standart) - use only 16px, 22px, 32px, 48px, 64px, 128px and 256px.

**Comment by varlesh** [comment]
Because Breeze icon theme not completed - have only 48px icon size

**Comment by psifidotos** [comment]
because of these differences in themes i will keep the same way to configure the icon size but I will update the internal code in order to do proper placement and fixing animations for no shadows choice...

First tests are ok... I am using Papirus icon theme in order to debug this...

**Comment by varlesh** [comment]
Please open, because not fixed. I like you dock, it's really very cool, but icons blurred.
Why icons not used fixed size 16px, 22px, 32px, 48px, 64px, 128px and 256px?
Compare with tasks on fullscreen mode.
Tasks (48px) - NowDock (0px) - yes, icons not blurred, but this not 48px size - it's maybe 64px (really maximize32px):
![64](https://cloud.githubusercontent.com/assets/8083855/17659660/cfd8e932-62dc-11e6-8035-2f9781049d8e.png)
Tasks (48px) - NowDock (-8px):
![48](https://cloud.githubusercontent.com/assets/8083855/17659718/0caf0a58-62dd-11e6-947d-3664128c9039.png)
Tasks (32px) - NowDock (-24px):
![32](https://cloud.githubusercontent.com/assets/8083855/17659754/4b7f97fc-62dd-11e6-915a-14c3c37928b1.png)
For example with Dolphin icon:
![123](https://cloud.githubusercontent.com/assets/8083855/17659900/4872dd8e-62de-11e6-9ad6-e7dd2e5db637.png)
You see, icons on NowDock blurred

**Comment by psifidotos** [comment]
1) I cant see any blurring in icons... I only see clearer contrast for Tasks because they use the dark panel beside them.. Add Icon Tasks in the Desktop with Now Dock above it... In order to compare... And try to use the same icon size... Let's see then...

2) What are the default icon sizes? I have seen so many themes with different sizes...
12,22,24,32,36,48,64,128,256

should I add all these? or should I benefit more a specific theme?
it's a difficult decision...

**Comment by varlesh** [comment]
1) Ok, see (open on new tab fullscreen mode)
![compare](https://cloud.githubusercontent.com/assets/8083855/17662376/b5750902-62ed-11e6-9729-dfd2eb070c58.png)

2) Size for icon will be hardcoded really. Usually on KDE use 16, **22**, 32, 48, 64,128, 256 for GTK DE 16, **24**, 32, 48,64,128,256.  Will be better use universal variant -  16,**22**,**24**,32,48,64,128,256.

**Comment by varlesh** [comment]
@psifidotos You see all icons blurred on NowDock? Maybe on dock use only one size, for example 32px, and scaling program method. Why **-24px** less then **-32px**, but **-16px** and **-8px** have almost equally one size on NowDock. Dock not use original size icons.

**Comment by psifidotos** [comment]
How can I debug this??? You should help me because my eye is very difficult to catch it....

I should describe you the internal... as a graphic designer you could understand what is probably happening...

1) The issue is blurring right? Not the icon sizes... correct? the icon sizes for this development cycle I am not interested in correcting it but the blurring is important... The user to have eye craspness...

Code internals...
The zoom effect is costly so I have to use buffers and shadows also is a bit costly... So what I do in the internals is the following...

the user chooses its preferred icon size, because the task is going to be zoomed at some I take an Image of a double size in order to show to the user... That image grows and shrinks....

In the default state this Image is in its half size, so this could be the blurring we are seeing here...

Does it make any sense? 
How to solve this, is a bit trickky...

What I could do for a start is to take the real Image in the real user preferred icon size, in order to check if this blur still exists... If it doesnt we can see what Image we will show for the zoomed item...

**Comment by psifidotos** [comment]
One idea also... What are your settings in icon sizes in plasma's systemsettings? 

the issue with the bigger icons in lower values does not appear in my system...
e.g. -24 to -32

**Comment by varlesh** [comment]
Zoom will be blurred icons always - it's normaly. But default icon (not zoomed) will be look as original icon on icon theme. Better create and check dock with full icon theme, for example Oxygen (have all needed icon sizes and standard icon theme for KDE):
![image](https://cloud.githubusercontent.com/assets/8083855/17662821/0843be8c-62f1-11e6-8028-ea87eb533cc5.png)
Also for compare and check dock work you can use Plank.
run plank from terminal and change icon size (we need only 16, 22, 32, 48, 64,128, 256.... note: on plank not available 16px and 22px icon sizes) 
`plank --preferences`

**Comment by psifidotos** [comment]
-24px
![image](https://cloud.githubusercontent.com/assets/2216474/17662924/a16003c8-62f1-11e6-85bc-8ac783ab68c9.png)

-32px
![image](https://cloud.githubusercontent.com/assets/2216474/17662948/bb3391ac-62f1-11e6-993e-80e59c2cb0f7.png)

**Comment by varlesh** [comment]
@psifidotos some icons (if you use Papirus) have line/lines, for example Dolphin, libreoffice icons.
See your screens libreoffice icon have blurred line

**Comment by varlesh** [comment]
![image](https://cloud.githubusercontent.com/assets/8083855/17663042/4a3f24b0-62f2-11e6-80db-41ceecf5d04f.png)

**Comment by varlesh** [comment]
NOTE: On papirus (kde-version) available for apps 16,22,32,48 and 64 px sizes.

**Comment by psifidotos** [comment]
I opened plank to compare.... You are right... My icons are blurred... Plank's are very craspy...
I have to investigate... Just using the default sizes may not solve this...

**Comment by varlesh** [comment]
For example Plank.
48px
![image](https://cloud.githubusercontent.com/assets/8083855/17663179/5002b5aa-62f3-11e6-910d-f216267ce0b4.png)
32px
![image](https://cloud.githubusercontent.com/assets/8083855/17663194/666aad16-62f3-11e6-83c6-d5c09d0a7bf9.png)

**Comment by psifidotos** [comment]
can you check the sharpness brach for this please? 
even though now the zoom effect looks blurred... I must find a way to update it...

**Comment by varlesh** [comment]
Yes, yes - now all fine. It's very good ))
![image](https://cloud.githubusercontent.com/assets/8083855/17665456/c785ce90-6303-11e6-9059-e6b0c7a3a172.png)

**Comment by varlesh** [comment]
@psifidotos Big thx, look cool. I like it 👍 
All size looks fine!!!

**Comment by varlesh** [comment]
Blurred zoom - it's normally, because there is a shift pixels.

**Comment by psifidotos** [comment]
@varlesh :+1:  Thank you for your support and patience... :)

it really looks lovely!!!

... for zooming blurring solution I might try to create a second buffer which is going to have an Image in the maximum zoomed area and use that for zooming.... it may help but I cant know yet...
