### ISSUE TITLE
Start application on pointer-release

### ISSUE THREAD

**Issue by Steinhagen** [psifidotos/nowdock-plasmoid#8]
The application should be started at pointer-release rather than at pointer-press. 
This is an accessibility issue for the scenario when you're trying to do a pointer-hold on the applet.

**Comment by psifidotos** [comment]
Are you describing the dragging when it should start? It conflicts with pointer-hold for applets?

**Comment by Steinhagen** [comment]
- First, the behavior is not consistent with the rest of plasma. For example, the applications from the icon task manager in plasma start when releasing the mouse button.
- Second, the current behavior of the applet makes displaying the context menu for widgets almost impossible. To reproduce this:
- Unlock widgets.
- Add the dock to the desktop as an applet (not inside of a panel).
- Press and hold an icon from the dock to display the applet options (Resize, Rotate, Now Dock Options). The options should be displayed instead of opening the application.

**Comment by psifidotos** [comment]
This is going to be fixed probably in the next release which is going to enable dragging...
--the onRelease event is already fixed... The applications launch after the release event...

Thanks a lot for the report because I had enabled dragging and was forcing the user in order to drag to pressandhold first... I will update this to be consistent with the inteface...

**Comment by Steinhagen** [comment]
I've checked the dragging branch and this is indeed fixed. Thanks for looking into this.

**Comment by psifidotos** [comment]
Thank you for your interest!!! 

regards,
michail
